### Creates a new survey
POST http://localhost:8000/surveys
content-type: application/json

{
    "question": "What is your favourite drink?",
    "options": [
        {
            "id": 1,
            "option": "Whiskey"
        },

        {
            "id": 2,
            "option": "Vodka"
        },
        {
            "id": 3,
            "option": "Coffee"
        }
    ]
}


### Gets all surveys
GET http://localhost:8000/surveys/


